# Part 0
Name: Oceana Zhu
NetID: oz2060

# Part 1

In [2]:
# Question 1
import numpy as np
import pandas as pd

Question 2:

In [3]:
#a
commute = [30,62,40,42,39]

In [4]:
#b
sum(commute)/len(commute)

42.6

On average, Charlie's commute is 42.6 minutes long.

In [5]:
#c
commute_array = np.array(commute)
print(commute_array)

[30 62 40 42 39]

In [6]:
#d
commute_array_seconds = [i * 60 for i in commute_array]
print(commute_array_seconds)

[1800, 3720, 2400, 2520, 2340]

In [7]:
#d
commute_seconds = [i * 60 for i in commute]
print(commute_seconds)

[1800, 3720, 2400, 2520, 2340]

Multiplying the numpy array by 60 does still give you the same answer.

In [52]:
#e
np.mean(commute_array)

42.6

On average, Charlie's commute is 42.6 minutes long.

In [9]:
#f
np.max(commute_array_seconds) - np.mean(commute_array_seconds)

1164.0

Charlie's longest commute time was longer than the average commute time by 1164 seconds.

In [10]:
#g
np.mean(commute_array_seconds) - np.min(commute_array_seconds)

756.0

Charlie's shortest commute time was shorter than his average commute time by 756 seconds.

Question 3

In [11]:
fave_westvillage_restaurants = ['tacombi', 'grey dog', 'chloe', 'pommes frites', 'pho bar']
len(fave_westvillage_restaurants)

5

Question 4

In [12]:
#a
beef = 11.48
ques = 9.62
salestax = 0.08875

print((beef+ques)*(1+salestax))

22.972625000000004

In [13]:
#b
subtotal = beef+ques
tip = 3.15
print(tip/subtotal)

0.14928909952606634

Explanation of process: 
For part a: The sales tax is applied on the bill as a whole before the tax. This means that we need to find the sum of all the goods purchased (beef and ques) and apply a sales tax to it. You need to add 1 to the value of the sales tax before multiplication because you are paying the full value of the beef and ques along with the sales tax. 

For part b: The tip is applied tothe bill before the tax. This means that we need to find the sum of all the goods purchased (subtotal value). We are given the value of the tip, thus, we divide this value by the subtotal to figure out how much of the total the tip was.

# Part 2

Question 5
Description of top50.csv: 
The top50 csv is a dataset that contains information about the top 50 songs. There are 13 variable and 50 songs analyzed. Instead of being presented in a table or chart, all of the values in this document are separated by commas.

Question 6

In [14]:
my_first_dataframe = pd.read_csv('shared/datasets/top50.csv')
my_first_dataframe

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
0,Se√±orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94
5,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102,68,80,-5,9,84,220,9,4,84
6,Ransom,Lil Tecca,trap music,180,64,75,-6,7,23,131,2,29,92
7,How Do You Sleep?,Sam Smith,pop,111,68,48,-5,8,35,202,15,9,90
8,Old Town Road - Remix,Lil Nas X,country rap,136,62,88,-6,11,64,157,5,10,87
9,bad guy,Billie Eilish,electropop,135,43,70,-11,10,56,194,33,38,95
10,Callaita,Bad Bunny,reggaeton,176,62,61,-5,24,24,251,60,31,93
11,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96,71,82,-4,15,38,185,28,7,86
12,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88
13,Otro Trago - Remix,Sech,panamanian pop,176,79,73,-2,6,76,288,7,20,87
14,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101,50,83,-4,12,10,205,10,5,92
15,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82
16,LA CANCI√ìN,J Balvin,latin,176,65,75,-6,11,43,243,15,32,90
17,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90,48,76,-6,7,91,158,56,5,91
18,Lalala,Y2K,canadian hip hop,130,39,84,-8,14,50,161,18,8,88
19,Truth Hurts,Lizzo,escape room,158,62,72,-3,12,41,173,11,11,91
20,Piece Of Your Heart,MEDUZA,pop house,124,74,68,-7,7,63,153,4,3,91
21,Panini,Lil Nas X,country rap,154,59,70,-6,12,48,115,34,8,91
22,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92,79,81,-4,9,58,309,14,7,83
23,Soltera - Remix,Lunay,latin,92,78,80,-4,44,80,266,36,4,91
24,bad guy (with Justin Bieber),Billie Eilish,electropop,135,45,67,-11,12,68,195,25,30,89
25,If I Can't Have You,Shawn Mendes,canadian pop,124,82,69,-4,13,87,191,49,6,70
26,Dance Monkey,Tones and I,australian pop,98,59,82,-6,18,54,210,69,10,83
27,It's You,Ali Gatie,canadian hip hop,96,46,73,-7,19,40,213,37,3,89
28,Con Calma,Daddy Yankee,latin,94,86,74,-3,6,66,193,11,6,91
29,QUE PRETENDES,J Balvin,latin,93,79,64,-4,36,94,222,3,25,89
30,Takeaway,The Chainsmokers,edm,85,51,29,-8,10,36,210,12,4,84
31,7 rings,Ariana Grande,dance pop,140,32,78,-11,9,33,179,59,33,89
32,0.958333333333333,Maluma,reggaeton,96,71,78,-5,9,68,176,22,28,89
33,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98,59,80,-7,13,18,200,2,15,89
34,Never Really Over,Katy Perry,dance pop,100,88,77,-5,32,39,224,19,6,89
35,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114,72,66,-7,14,32,164,18,6,89
36,Otro Trago,Sech,panamanian pop,176,70,75,-5,11,62,226,14,34,91
37,Antisocial (with Travis Scott),Ed Sheeran,pop,152,82,72,-5,36,91,162,13,5,87
38,Sucker,Jonas Brothers,boy band,138,73,84,-5,11,95,181,4,6,80
39,"fuck, i'm lonely (with Anne-Marie) - from ‚Äú13 ...",Lauv,dance pop,95,56,81,-6,6,68,199,48,7,78
40,Higher Love,Kygo,edm,104,68,69,-7,10,40,228,2,3,88
41,You Need To Calm Down,Taylor Swift,dance pop,85,68,77,-6,7,73,171,1,5,90
42,Shallow,Lady Gaga,dance pop,96,39,57,-6,23,32,216,37,3,87
43,Talk,Khalid,pop,136,40,90,-9,6,35,198,5,13,84
44,Con Altura,ROSAL√çA,r&b en espanol,98,69,88,-4,5,75,162,39,12,88
45,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88
46,Te Robar√©,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88
47,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,88
48,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88
49,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82

Kind of information contained in the dataframe: The dataframe contains information about the 50 top songs. It breaks down quantitative data about the songs, such as the beats per minute, but also qualitative data measured on a scale, such as danceability. Furthermore, there is also general information about the song, such as its name and artist.

Question 7

In [15]:
print( my_first_dataframe.shape )
print( my_first_dataframe.columns )
print( my_first_dataframe.dtypes )

(50, 13)
Index(['TrackName', 'ArtistName', 'Genre', 'BeatsPerMinute', 'Energy',
       'Danceability', 'LoudnessdB', 'Liveness', 'Valence', 'Length',
       'Acousticness', 'Speechiness', 'Popularity'],
      dtype='object')
TrackName         object
ArtistName        object
Genre             object
BeatsPerMinute     int64
Energy             int64
Danceability       int64
LoudnessdB         int64
Liveness           int64
Valence            int64
Length             int64
Acousticness       int64
Speechiness        int64
Popularity         int64
dtype: object

What I learned about the dataframe: I learned that this dataframe has 13 columns and 50 observations or rows. I also learned the differnt names of the columns and the type of data that is recorded by each variable.

Question 8

In [16]:
my_first_dataframe.head()

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
0,Se√±orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94

In [17]:
my_first_dataframe.tail()

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
45,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88
46,Te Robar√©,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88
47,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,88
48,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88
49,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82

In [18]:
my_first_dataframe.head(3)

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
0,Se√±orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85

In [19]:
my_first_dataframe.head(2)

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
0,Se√±orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92

In [20]:
my_first_dataframe.tail(2)

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
48,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88
49,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82

In [21]:
my_first_dataframe.tail(3)

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
47,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,88
48,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88
49,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82

In [22]:
my_first_dataframe.sample(5)

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
15,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82
12,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88
33,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98,59,80,-7,13,18,200,2,15,89
30,Takeaway,The Chainsmokers,edm,85,51,29,-8,10,36,210,12,4,84
9,bad guy,Billie Eilish,electropop,135,43,70,-11,10,56,194,33,38,95

In [23]:
my_first_dataframe.sample(3)

,TrackName,ArtistName,Genre,BeatsPerMinute,Energy,Danceability,LoudnessdB,Liveness,Valence,Length,Acousticness,Speechiness,Popularity
12,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88
41,You Need To Calm Down,Taylor Swift,dance pop,85,68,77,-6,7,73,171,1,5,90
34,Never Really Over,Katy Perry,dance pop,100,88,77,-5,32,39,224,19,6,89

What was done by each of the commands: The head command extracted the first n rows from a dataset. The tail command extracted the last n rows from a dataset. The sample command extracted a random sample of n rows from a dataset.

# Part 3

Question 9

In [24]:
bronx_pop_density = pd.read_csv('https://bronx.lehman.cuny.edu/api/views/2q3n-mzjq/rows.csv?accessType=DOWNLOAD')

In [25]:
bronx_pop_density.head(2)

,Zipcode,County and Neighborhood,Total Area Sq.Miles,Total Area Sq.Yard,Pop.Density per Sq Mile,Pop.Density per Sq Yard,Total Population 2010,Pop. Age 65 and Up,Pop. Under 18,Households,...,Age 65 and Up: % Live Alone,Age 65 and Up: % Live in Fams,Age 65 and Up: % in Gp.Quarters,% Kids Live w/Ma+Pa,% Kids Live w/Ma Only,% Kids Live w/Grandparents,% Kids Live in Group Quarters,Housing Units,% Rental Units,Location 1
0,10452,Bronx High Bridge,0.98,3035648.0,76909.1837,0.0248,75371,5237,22527,24796,...,30.3,64.6,0.1,32.3,41.5,10.8,1.6,25866,92.8,"(40.83724, -73.9211399997)"
1,10453,Bronx Morris Hts,0.92,2849792.0,85118.4783,0.0275,78309,5056,23464,25307,...,27.5,67.1,0.4,27.3,46.3,11.8,1.6,27018,89.4,"(40.8522899998, -73.9109799997)"

In [26]:
bronx_pop_density.tail(2)

,Zipcode,County and Neighborhood,Total Area Sq.Miles,Total Area Sq.Yard,Pop.Density per Sq Mile,Pop.Density per Sq Yard,Total Population 2010,Pop. Age 65 and Up,Pop. Under 18,Households,...,Age 65 and Up: % Live Alone,Age 65 and Up: % Live in Fams,Age 65 and Up: % in Gp.Quarters,% Kids Live w/Ma+Pa,% Kids Live w/Ma Only,% Kids Live w/Grandparents,% Kids Live in Group Quarters,Housing Units,% Rental Units,Location 1
23,10475,Bronx Coop City,1.82,5637632.0,22489.5604,0.0073,40931,8760,7513,18534,...,37.0,52.0,8.5,39.2,32.9,14.2,1.6,18911,51.3,"(40.8728999996, -73.8270299999)"
24,10451,Bronx Melrose,1.02,3159552.0,44816.6667,0.0145,45713,5453,12444,17106,...,42.8,52.7,0.8,28.2,45.7,14.1,0.2,17779,82.7,"(40.8221799998, -73.9209600004)"

Describe what information is contained in this data frame: This data frame contains information about the the demographics of the population in the Bronx, broken down by neighborhood. The data frame contains information about race, age, family size, housing, and general information about the area.

Question 10:
How many rows and columns are there in this dataset? There are 25 rows and 50 columns. 
State three of the column names and their corresponding data types
Three column names are Zipcode, Country and Neighborhood, and Total Area Sq.Miles. Their corresponding data types are integer, text, and floating point number.

In [27]:
print( bronx_pop_density.shape )
print( bronx_pop_density.dtypes )

(25, 50)
Zipcode                              int64
County and Neighborhood             object
Total Area Sq.Miles                float64
Total Area Sq.Yard                 float64
Pop.Density per Sq Mile            float64
Pop.Density per Sq Yard            float64
Total Population 2010                int64
Pop. Age 65 and Up                   int64
Pop. Under 18                        int64
Households                           int64
Families                             int64
Non-Hispanic Whites                  int64
Non-Hispanic Blacks                  int64
Non-Hispanic Asians                  int64
Hispanics                            int64
% Non-Hisp. Whites                 float64
% Non-Hisp. Blacks                 float64
% Non-Hisp.Asians                  float64
% Hispanics                        float64
% Two or More Races                float64
Median Age: Blacks                 float64
Median Age: Asians                 float64
Median Age: Hispanics              float64
Med.Age: Non-Hisp.Whites           float64
% of Pop. From India               float64
% from Bangladesh                  float64
% Chinese                          float64
% Filipinos                        float64
% Koreans                          float64
% from Pakistan                    float64
% from Vietnam                     float64
% Mexicans in Pop                  float64
% Puerto Ricans in Pop             float64
% Cubans in Pop                    float64
% Dominicans in Pop                float64
% from Guatemala                   float64
% from Honduras                    float64
% from Colombia                    float64
% from Ecuador                     float64
% Peruvians in Pop                 float64
Age 65 and Up: % Live Alone        float64
Age 65 and Up: % Live in Fams      float64
Age 65 and Up: % in Gp.Quarters    float64
% Kids Live w/Ma+Pa                float64
% Kids Live w/Ma Only              float64
% Kids Live w/Grandparents         float64
% Kids Live in Group Quarters      float64
Housing Units                        int64
% Rental Units                     float64
Location 1                          object
dtype: object

Question 11
a - Create a new column called fraction_under18, which contains the fraction of each zipcode's population who are under 18
b - Which zipcode has the highest fraction of residents under 18? Is this zipcode a lot ‚Äúyounger‚Äù than other zipcodes in the Bronx? Use a dataframe method to sort the rows.

In [32]:
#a
bronx_pop_density['fraction_under18'] = bronx_pop_density['Pop. Under 18'] / bronx_pop_density['Total Population 2010']
#b
bronx_pop_density.sort_values (by ='fraction_under18', axis=0, ascending=False)

,Zipcode,County and Neighborhood,Total Area Sq.Miles,Total Area Sq.Yard,Pop.Density per Sq Mile,Pop.Density per Sq Yard,Total Population 2010,Pop. Age 65 and Up,Pop. Under 18,Households,...,Age 65 and Up: % Live in Fams,Age 65 and Up: % in Gp.Quarters,% Kids Live w/Ma+Pa,% Kids Live w/Ma Only,% Kids Live w/Grandparents,% Kids Live in Group Quarters,Housing Units,% Rental Units,Location 1,fraction_under18
5,10457,Bronx Tremont,1.06,3283456.0,66505.6604,0.0215,70496,5304,21943,22873,...,57.4,4.4,27.9,46.7,9.7,3.6,24364,87.3,"(40.8476400003, -73.89989)",0.311266
4,10456,Bronx Morrisania,1.02,3159552.0,84850.0000,0.0274,86547,6713,26930,28122,...,56.5,9.4,29.7,46.6,11.1,1.1,29651,89.1,"(40.8308399999, -73.9097899997)",0.311160
7,10459,Bronx Boulevd-Longwood,0.82,2540032.0,57692.6829,0.0186,47308,3957,14616,15398,...,58.6,4.4,27.6,47.4,10.6,2.6,16496,83.3,"(40.8251799997, -73.8941699997)",0.308954
8,10460,Bronx West Farms,1.32,4088832.0,43417.4242,0.0140,57311,4897,17545,19512,...,61.9,0.2,27.3,48.5,10.5,2.5,20706,84.7,"(40.8404800002, -73.8802600004)",0.306137
2,10454,Bronx Mott Haven,1.04,3221504.0,35900.9615,0.0116,37337,3378,11397,11978,...,57.3,1.2,26.1,45.6,13.4,2.8,12772,88.7,"(40.8075800001, -73.9184800003)",0.305247
22,10474,Bronx Hunts Point,1.53,4739328.0,8026.7974,0.0026,12281,750,3684,3633,...,63.3,1.3,29.1,48.5,10.0,1.5,3985,83.8,"(40.8139299998, -73.8866399996)",0.299976
1,10453,Bronx Morris Hts,0.92,2849792.0,85118.4783,0.0275,78309,5056,23464,25307,...,67.1,0.4,27.3,46.3,11.8,1.6,27018,89.4,"(40.8522899998, -73.9109799997)",0.299634
3,10455,Bronx Hub,0.71,2199296.0,55866.1972,0.0180,39665,3478,11880,12880,...,61.2,0.7,27.3,45.5,12.1,2.9,13851,86.1,"(40.8151399998, -73.9078500002)",0.299508
0,10452,Bronx High Bridge,0.98,3035648.0,76909.1837,0.0248,75371,5237,22527,24796,...,64.6,0.1,32.3,41.5,10.8,1.6,25866,92.8,"(40.83724, -73.9211399997)",0.298882
6,10458,Bronx Fordham,1.01,3128576.0,78704.9505,0.0254,79492,5213,22550,26201,...,61.6,1.2,33.2,43.7,9.3,0.4,27806,89.9,"(40.8630699996, -73.8891599998)",0.283676
20,10472,Bronx Bruckner,1.05,3252480.0,63198.0952,0.0204,66358,6256,18609,22002,...,64.2,2.7,33.4,40.8,10.6,1.3,23386,80.2,"(40.8293900004, -73.8715400003)",0.280433
16,10468,Bronx Jerome,1.09,3376384.0,69819.2661,0.0225,76103,6491,20748,24909,...,54.6,13.0,32.0,41.0,11.3,1.1,26178,86.4,"(40.8663499998, -73.8999199996)",0.272631
24,10451,Bronx Melrose,1.02,3159552.0,44816.6667,0.0145,45713,5453,12444,17106,...,52.7,0.8,28.2,45.7,14.1,0.2,17779,82.7,"(40.8221799998, -73.9209600004)",0.272220
21,10473,Bronx Soundview,2.19,6783744.0,26721.0046,0.0086,58519,6969,15800,20571,...,65.4,2.4,31.3,43.5,13.8,0.0,21323,71.9,"(40.8190199998, -73.8605499998)",0.269998
15,10467,Bronx Williamsbridge,2.33,7217408.0,41656.6524,0.0134,97060,9651,25515,35524,...,52.0,12.0,37.4,40.5,9.1,0.1,37432,83.2,"(40.8733400001, -73.8718599997)",0.262879
14,10466,Bronx Wakefield,2.02,6257152.0,33570.7921,0.0108,67813,7352,17808,23318,...,66.2,5.3,32.6,41.1,12.8,0.3,24854,62.8,"(40.8907000003, -73.8511600002)",0.262605
17,10469,Bronx Baychester,2.48,7682048.0,26867.3387,0.0087,66631,9536,16060,22554,...,58.8,18.4,41.2,33.3,11.4,1.1,24078,52.2,"(40.8709, -73.8493700004)",0.241029
10,10462,Bronx Parkchester,1.48,4584448.0,51205.4054,0.0165,75784,7795,18100,29855,...,60.1,2.4,47.0,33.1,7.4,0.0,31331,74.5,"(40.8434100004, -73.8597099997)",0.238837
11,10463,Bronx Kingsbridge,1.58,4894208.0,37662.6582,0.0122,59507,11811,13779,28408,...,49.3,12.6,48.8,33.2,8.0,0.0,30368,65.2,"(40.8813400003, -73.9061799996)",0.231553
18,10470,Bronx Woodlawn,1.43,4429568.0,10694.4056,0.0035,15293,2196,3239,6390,...,58.4,0.4,47.6,33.8,7.3,0.7,6882,63.1,"(40.9006099996, -73.8607999996)",0.211796
13,10465,Bronx Throgs Neck,3.43,10624768.0,12311.9534,0.0040,42230,6643,8908,15770,...,63.5,6.8,55.3,27.0,8.1,0.0,16889,44.7,"(40.8255800001, -73.8195799999)",0.210940
9,10461,Bronx Westchester,2.40,7434240.0,21042.5000,0.0068,50502,7581,10298,19772,...,58.0,7.2,56.8,25.9,6.6,0.7,21127,64.9,"(40.8457799999, -73.8401899998)",0.203913
23,10475,Bronx Coop City,1.82,5637632.0,22489.5604,0.0073,40931,8760,7513,18534,...,52.0,8.5,39.2,32.9,14.2,1.6,18911,51.3,"(40.8728999996, -73.8270299999)",0.183553
12,10464,Bronx City Island,3.59,11120384.0,1262.9526,0.0004,4534,917,787,2089,...,53.3,0.1,64.9,19.2,7.5,0.0,2272,41.5,"(40.8488900004, -73.7880700001)",0.173577
19,10471,Bronx Riverdale,2.59,8022784.0,8850.1931,0.0029,22922,5376,3700,9305,...,36.8,24.7,73.1,16.6,2.9,0.9,10054,47.2,"(40.90097, -73.9034800001)",0.161417

10457 is the zip code with the highest fraction of residents under 18. I would say that this zipcode is "younger" than other zipcodes because it has the greatest percentage of its population under the age of 18.

Question 12
Please formulate a question that can be answered by creating a new column in the above data frame. (The process would be similar to the above exercise, but you are asked to come up with your own question!) Please include the python codes/commands as well as a text summary of both your question and the answer

Another question that can be answered is: What zipcode has the greatest percentage of residents above the age of 65.

In [34]:
bronx_pop_density['fraction_above65'] = bronx_pop_density['Pop. Age 65 and Up'] / bronx_pop_density['Total Population 2010']
bronx_pop_density.sort_values (by ='fraction_above65', axis=0, ascending=False)

,Zipcode,County and Neighborhood,Total Area Sq.Miles,Total Area Sq.Yard,Pop.Density per Sq Mile,Pop.Density per Sq Yard,Total Population 2010,Pop. Age 65 and Up,Pop. Under 18,Households,...,Age 65 and Up: % in Gp.Quarters,% Kids Live w/Ma+Pa,% Kids Live w/Ma Only,% Kids Live w/Grandparents,% Kids Live in Group Quarters,Housing Units,% Rental Units,Location 1,fraction_under18,fraction_above65
19,10471,Bronx Riverdale,2.59,8022784.0,8850.1931,0.0029,22922,5376,3700,9305,...,24.7,73.1,16.6,2.9,0.9,10054,47.2,"(40.90097, -73.9034800001)",0.161417,0.234535
23,10475,Bronx Coop City,1.82,5637632.0,22489.5604,0.0073,40931,8760,7513,18534,...,8.5,39.2,32.9,14.2,1.6,18911,51.3,"(40.8728999996, -73.8270299999)",0.183553,0.214019
12,10464,Bronx City Island,3.59,11120384.0,1262.9526,0.0004,4534,917,787,2089,...,0.1,64.9,19.2,7.5,0.0,2272,41.5,"(40.8488900004, -73.7880700001)",0.173577,0.202250
11,10463,Bronx Kingsbridge,1.58,4894208.0,37662.6582,0.0122,59507,11811,13779,28408,...,12.6,48.8,33.2,8.0,0.0,30368,65.2,"(40.8813400003, -73.9061799996)",0.231553,0.198481
13,10465,Bronx Throgs Neck,3.43,10624768.0,12311.9534,0.0040,42230,6643,8908,15770,...,6.8,55.3,27.0,8.1,0.0,16889,44.7,"(40.8255800001, -73.8195799999)",0.210940,0.157305
9,10461,Bronx Westchester,2.40,7434240.0,21042.5000,0.0068,50502,7581,10298,19772,...,7.2,56.8,25.9,6.6,0.7,21127,64.9,"(40.8457799999, -73.8401899998)",0.203913,0.150113
18,10470,Bronx Woodlawn,1.43,4429568.0,10694.4056,0.0035,15293,2196,3239,6390,...,0.4,47.6,33.8,7.3,0.7,6882,63.1,"(40.9006099996, -73.8607999996)",0.211796,0.143595
17,10469,Bronx Baychester,2.48,7682048.0,26867.3387,0.0087,66631,9536,16060,22554,...,18.4,41.2,33.3,11.4,1.1,24078,52.2,"(40.8709, -73.8493700004)",0.241029,0.143117
24,10451,Bronx Melrose,1.02,3159552.0,44816.6667,0.0145,45713,5453,12444,17106,...,0.8,28.2,45.7,14.1,0.2,17779,82.7,"(40.8221799998, -73.9209600004)",0.272220,0.119288
21,10473,Bronx Soundview,2.19,6783744.0,26721.0046,0.0086,58519,6969,15800,20571,...,2.4,31.3,43.5,13.8,0.0,21323,71.9,"(40.8190199998, -73.8605499998)",0.269998,0.119090
14,10466,Bronx Wakefield,2.02,6257152.0,33570.7921,0.0108,67813,7352,17808,23318,...,5.3,32.6,41.1,12.8,0.3,24854,62.8,"(40.8907000003, -73.8511600002)",0.262605,0.108416
10,10462,Bronx Parkchester,1.48,4584448.0,51205.4054,0.0165,75784,7795,18100,29855,...,2.4,47.0,33.1,7.4,0.0,31331,74.5,"(40.8434100004, -73.8597099997)",0.238837,0.102858
15,10467,Bronx Williamsbridge,2.33,7217408.0,41656.6524,0.0134,97060,9651,25515,35524,...,12.0,37.4,40.5,9.1,0.1,37432,83.2,"(40.8733400001, -73.8718599997)",0.262879,0.099433
20,10472,Bronx Bruckner,1.05,3252480.0,63198.0952,0.0204,66358,6256,18609,22002,...,2.7,33.4,40.8,10.6,1.3,23386,80.2,"(40.8293900004, -73.8715400003)",0.280433,0.094277
2,10454,Bronx Mott Haven,1.04,3221504.0,35900.9615,0.0116,37337,3378,11397,11978,...,1.2,26.1,45.6,13.4,2.8,12772,88.7,"(40.8075800001, -73.9184800003)",0.305247,0.090473
3,10455,Bronx Hub,0.71,2199296.0,55866.1972,0.0180,39665,3478,11880,12880,...,0.7,27.3,45.5,12.1,2.9,13851,86.1,"(40.8151399998, -73.9078500002)",0.299508,0.087684
8,10460,Bronx West Farms,1.32,4088832.0,43417.4242,0.0140,57311,4897,17545,19512,...,0.2,27.3,48.5,10.5,2.5,20706,84.7,"(40.8404800002, -73.8802600004)",0.306137,0.085446
16,10468,Bronx Jerome,1.09,3376384.0,69819.2661,0.0225,76103,6491,20748,24909,...,13.0,32.0,41.0,11.3,1.1,26178,86.4,"(40.8663499998, -73.8999199996)",0.272631,0.085292
7,10459,Bronx Boulevd-Longwood,0.82,2540032.0,57692.6829,0.0186,47308,3957,14616,15398,...,4.4,27.6,47.4,10.6,2.6,16496,83.3,"(40.8251799997, -73.8941699997)",0.308954,0.083643
4,10456,Bronx Morrisania,1.02,3159552.0,84850.0000,0.0274,86547,6713,26930,28122,...,9.4,29.7,46.6,11.1,1.1,29651,89.1,"(40.8308399999, -73.9097899997)",0.311160,0.077565
5,10457,Bronx Tremont,1.06,3283456.0,66505.6604,0.0215,70496,5304,21943,22873,...,4.4,27.9,46.7,9.7,3.6,24364,87.3,"(40.8476400003, -73.89989)",0.311266,0.075238
0,10452,Bronx High Bridge,0.98,3035648.0,76909.1837,0.0248,75371,5237,22527,24796,...,0.1,32.3,41.5,10.8,1.6,25866,92.8,"(40.83724, -73.9211399997)",0.298882,0.069483
6,10458,Bronx Fordham,1.01,3128576.0,78704.9505,0.0254,79492,5213,22550,26201,...,1.2,33.2,43.7,9.3,0.4,27806,89.9,"(40.8630699996, -73.8891599998)",0.283676,0.065579
1,10453,Bronx Morris Hts,0.92,2849792.0,85118.4783,0.0275,78309,5056,23464,25307,...,0.4,27.3,46.3,11.8,1.6,27018,89.4,"(40.8522899998, -73.9109799997)",0.299634,0.064565
22,10474,Bronx Hunts Point,1.53,4739328.0,8026.7974,0.0026,12281,750,3684,3633,...,1.3,29.1,48.5,10.0,1.5,3985,83.8,"(40.8139299998, -73.8866399996)",0.299976,0.061070

The answer to the question of which zip code has the oldest population can be answered by creating a new column that calculates the fraction of the total population of that area that is above the age of 65. The answer to this question is 10471 because they had the greatest fraction of people above the age of 65.

Question 13
Suppose that we are interested in finding out the percentage of the population in Bronx Kingsbridge who stated that they belong to two or more races. Type a python code/command that extracts the above number from the dataframe. Please very briefly describe how you think about this question.

In [36]:
print(bronx_pop_density[bronx_pop_density['County and Neighborhood']=='Bronx Kingsbridge'].index.values)

[11]

In [37]:
bronx_pop_density.loc[11,"% Two or More Races"]

5.0

I thought about this question by thinking about the fact that I have to locate a value given the fact that we are interested in the county of Bronx Kingsbridge. Thus, I found the index of Bronx Kingsbridge and located the value of "% Two or More Races" at that index value for Bronx Kingsbridge.

Question 14
Pick two columns (your choice) and simultaneously sort bronx pop density based on values in these two columns; one in ascending order and the other in descending order. In the ‚Äúwriting‚Äù portion of this question, briefly summarize what you did (that is, state which two columns you pick, etc.). Does the resulting sorted data frame match what you expected to see?

In [49]:
bronx_pop_density.sort_values(by=['Housing Units', '% Rental Units'], ascending=[True, False])

,Zipcode,County and Neighborhood,Total Area Sq.Miles,Total Area Sq.Yard,Pop.Density per Sq Mile,Pop.Density per Sq Yard,Total Population 2010,Pop. Age 65 and Up,Pop. Under 18,Households,...,Age 65 and Up: % in Gp.Quarters,% Kids Live w/Ma+Pa,% Kids Live w/Ma Only,% Kids Live w/Grandparents,% Kids Live in Group Quarters,Housing Units,% Rental Units,Location 1,fraction_under18,fraction_above65
12,10464,Bronx City Island,3.59,11120384.0,1262.9526,0.0004,4534,917,787,2089,...,0.1,64.9,19.2,7.5,0.0,2272,41.5,"(40.8488900004, -73.7880700001)",0.173577,0.202250
22,10474,Bronx Hunts Point,1.53,4739328.0,8026.7974,0.0026,12281,750,3684,3633,...,1.3,29.1,48.5,10.0,1.5,3985,83.8,"(40.8139299998, -73.8866399996)",0.299976,0.061070
18,10470,Bronx Woodlawn,1.43,4429568.0,10694.4056,0.0035,15293,2196,3239,6390,...,0.4,47.6,33.8,7.3,0.7,6882,63.1,"(40.9006099996, -73.8607999996)",0.211796,0.143595
19,10471,Bronx Riverdale,2.59,8022784.0,8850.1931,0.0029,22922,5376,3700,9305,...,24.7,73.1,16.6,2.9,0.9,10054,47.2,"(40.90097, -73.9034800001)",0.161417,0.234535
2,10454,Bronx Mott Haven,1.04,3221504.0,35900.9615,0.0116,37337,3378,11397,11978,...,1.2,26.1,45.6,13.4,2.8,12772,88.7,"(40.8075800001, -73.9184800003)",0.305247,0.090473
3,10455,Bronx Hub,0.71,2199296.0,55866.1972,0.0180,39665,3478,11880,12880,...,0.7,27.3,45.5,12.1,2.9,13851,86.1,"(40.8151399998, -73.9078500002)",0.299508,0.087684
7,10459,Bronx Boulevd-Longwood,0.82,2540032.0,57692.6829,0.0186,47308,3957,14616,15398,...,4.4,27.6,47.4,10.6,2.6,16496,83.3,"(40.8251799997, -73.8941699997)",0.308954,0.083643
13,10465,Bronx Throgs Neck,3.43,10624768.0,12311.9534,0.0040,42230,6643,8908,15770,...,6.8,55.3,27.0,8.1,0.0,16889,44.7,"(40.8255800001, -73.8195799999)",0.210940,0.157305
24,10451,Bronx Melrose,1.02,3159552.0,44816.6667,0.0145,45713,5453,12444,17106,...,0.8,28.2,45.7,14.1,0.2,17779,82.7,"(40.8221799998, -73.9209600004)",0.272220,0.119288
23,10475,Bronx Coop City,1.82,5637632.0,22489.5604,0.0073,40931,8760,7513,18534,...,8.5,39.2,32.9,14.2,1.6,18911,51.3,"(40.8728999996, -73.8270299999)",0.183553,0.214019
8,10460,Bronx West Farms,1.32,4088832.0,43417.4242,0.0140,57311,4897,17545,19512,...,0.2,27.3,48.5,10.5,2.5,20706,84.7,"(40.8404800002, -73.8802600004)",0.306137,0.085446
9,10461,Bronx Westchester,2.40,7434240.0,21042.5000,0.0068,50502,7581,10298,19772,...,7.2,56.8,25.9,6.6,0.7,21127,64.9,"(40.8457799999, -73.8401899998)",0.203913,0.150113
21,10473,Bronx Soundview,2.19,6783744.0,26721.0046,0.0086,58519,6969,15800,20571,...,2.4,31.3,43.5,13.8,0.0,21323,71.9,"(40.8190199998, -73.8605499998)",0.269998,0.119090
20,10472,Bronx Bruckner,1.05,3252480.0,63198.0952,0.0204,66358,6256,18609,22002,...,2.7,33.4,40.8,10.6,1.3,23386,80.2,"(40.8293900004, -73.8715400003)",0.280433,0.094277
17,10469,Bronx Baychester,2.48,7682048.0,26867.3387,0.0087,66631,9536,16060,22554,...,18.4,41.2,33.3,11.4,1.1,24078,52.2,"(40.8709, -73.8493700004)",0.241029,0.143117
5,10457,Bronx Tremont,1.06,3283456.0,66505.6604,0.0215,70496,5304,21943,22873,...,4.4,27.9,46.7,9.7,3.6,24364,87.3,"(40.8476400003, -73.89989)",0.311266,0.075238
14,10466,Bronx Wakefield,2.02,6257152.0,33570.7921,0.0108,67813,7352,17808,23318,...,5.3,32.6,41.1,12.8,0.3,24854,62.8,"(40.8907000003, -73.8511600002)",0.262605,0.108416
0,10452,Bronx High Bridge,0.98,3035648.0,76909.1837,0.0248,75371,5237,22527,24796,...,0.1,32.3,41.5,10.8,1.6,25866,92.8,"(40.83724, -73.9211399997)",0.298882,0.069483
16,10468,Bronx Jerome,1.09,3376384.0,69819.2661,0.0225,76103,6491,20748,24909,...,13.0,32.0,41.0,11.3,1.1,26178,86.4,"(40.8663499998, -73.8999199996)",0.272631,0.085292
1,10453,Bronx Morris Hts,0.92,2849792.0,85118.4783,0.0275,78309,5056,23464,25307,...,0.4,27.3,46.3,11.8,1.6,27018,89.4,"(40.8522899998, -73.9109799997)",0.299634,0.064565
6,10458,Bronx Fordham,1.01,3128576.0,78704.9505,0.0254,79492,5213,22550,26201,...,1.2,33.2,43.7,9.3,0.4,27806,89.9,"(40.8630699996, -73.8891599998)",0.283676,0.065579
4,10456,Bronx Morrisania,1.02,3159552.0,84850.0000,0.0274,86547,6713,26930,28122,...,9.4,29.7,46.6,11.1,1.1,29651,89.1,"(40.8308399999, -73.9097899997)",0.311160,0.077565
11,10463,Bronx Kingsbridge,1.58,4894208.0,37662.6582,0.0122,59507,11811,13779,28408,...,12.6,48.8,33.2,8.0,0.0,30368,65.2,"(40.8813400003, -73.9061799996)",0.231553,0.198481
10,10462,Bronx Parkchester,1.48,4584448.0,51205.4054,0.0165,75784,7795,18100,29855,...,2.4,47.0,33.1,7.4,0.0,31331,74.5,"(40.8434100004, -73.8597099997)",0.238837,0.102858
15,10467,Bronx Williamsbridge,2.33,7217408.0,41656.6524,0.0134,97060,9651,25515,35524,...,12.0,37.4,40.5,9.1,0.1,37432,83.2,"(40.8733400001, -73.8718599997)",0.262879,0.099433

I sorted Housing Units in descending order and % Rental Units by ascending order. The dataframe almost matches what I expected to see because I was unsure how the second column would be sorted but thought that its sorting would be limited by the sorting of the first column. As such, I observed that while Housing Units were ordered from lowest to highest, % Rental Units wasn't perfectly ordered highest to lowest because it was constrained by the ordering of the Housing Units column.

Question 15
Create a data frame called bronx pop density rental filtered containing only rows where the percentage of rental units are 70 or above. Then, determine how many percent of all neighborhoods/zipcodes in the Bronx satisfy the above criteria (70 percent or more of its housing unit are rentals). Please briefly describe how you approach this question.

In [50]:
bronx_pop_density_rental_filtered = bronx_pop_density[bronx_pop_density["% Rental Units"] >= 70]
print(bronx_pop_density_rental_filtered)

    Zipcode County and Neighborhood  Total Area Sq.Miles      \
0     10452       Bronx High Bridge                     0.98
1     10453        Bronx Morris Hts                     0.92
2     10454        Bronx Mott Haven                     1.04
3     10455               Bronx Hub                     0.71
4     10456        Bronx Morrisania                     1.02
5     10457           Bronx Tremont                     1.06
6     10458           Bronx Fordham                     1.01
7     10459  Bronx Boulevd-Longwood                     0.82
8     10460        Bronx West Farms                     1.32
10    10462       Bronx Parkchester                     1.48
15    10467    Bronx Williamsbridge                     2.33
16    10468            Bronx Jerome                     1.09
20    10472          Bronx Bruckner                     1.05
21    10473         Bronx Soundview                     2.19
22    10474       Bronx Hunts Point                     1.53
24    10451           Bronx Melrose                     1.02

    Total Area Sq.Yard  Pop.Density per Sq Mile  Pop.Density per Sq Yard  \
0            3035648.0               76909.1837                   0.0248
1            2849792.0               85118.4783                   0.0275
2            3221504.0               35900.9615                   0.0116
3            2199296.0               55866.1972                   0.0180
4            3159552.0               84850.0000                   0.0274
5            3283456.0               66505.6604                   0.0215
6            3128576.0               78704.9505                   0.0254
7            2540032.0               57692.6829                   0.0186
8            4088832.0               43417.4242                   0.0140
10           4584448.0               51205.4054                   0.0165
15           7217408.0               41656.6524                   0.0134
16           3376384.0               69819.2661                   0.0225
20           3252480.0               63198.0952                   0.0204
21           6783744.0               26721.0046                   0.0086
22           4739328.0                8026.7974                   0.0026
24           3159552.0               44816.6667                   0.0145

    Total Population 2010  Pop. Age 65 and Up  Pop. Under 18  Households  ...  \
0                   75371                5237          22527       24796  ...
1                   78309                5056          23464       25307  ...
2                   37337                3378          11397       11978  ...
3                   39665                3478          11880       12880  ...
4                   86547                6713          26930       28122  ...
5                   70496                5304          21943       22873  ...
6                   79492                5213          22550       26201  ...
7                   47308                3957          14616       15398  ...
8                   57311                4897          17545       19512  ...
10                  75784                7795          18100       29855  ...
15                  97060                9651          25515       35524  ...
16                  76103                6491          20748       24909  ...
20                  66358                6256          18609       22002  ...
21                  58519                6969          15800       20571  ...
22                  12281                 750           3684        3633  ...
24                  45713                5453          12444       17106  ...

    Age 65 and Up: % in Gp.Quarters  % Kids Live w/Ma+Pa  \
0                               0.1                 32.3
1                               0.4                 27.3
2                               1.2                 26.1
3                               0.7                 27.3
4                               9.4                 29.7
5                               4.4                 27.9
6                               1.2                 33.2
7                               4.4                 27.6
8                               0.2                 27.3
10                              2.4                 47.0
15                             12.0                 37.4
16                             13.0                 32.0
20                              2.7                 33.4
21                              2.4                 31.3
22                              1.3                 29.1
24                              0.8                 28.2

    % Kids Live w/Ma Only  % Kids Live w/Grandparents  \
0                    41.5                        10.8
1                    46.3                        11.8
2                    45.6                        13.4
3                    45.5                        12.1
4                    46.6                        11.1
5                    46.7                         9.7
6                    43.7                         9.3
7                    47.4                        10.6
8                    48.5                        10.5
10                   33.1                         7.4
15                   40.5                         9.1
16                   41.0                        11.3
20                   40.8                        10.6
21                   43.5                        13.8
22                   48.5                        10.0
24                   45.7                        14.1

    % Kids Live in Group Quarters  Housing Units  % Rental Units  \
0                             1.6          25866            92.8
1                             1.6          27018            89.4
2                             2.8          12772            88.7
3                             2.9          13851            86.1
4                             1.1          29651            89.1
5                             3.6          24364            87.3
6                             0.4          27806            89.9
7                             2.6          16496            83.3
8                             2.5          20706            84.7
10                            0.0          31331            74.5
15                            0.1          37432            83.2
16                            1.1          26178            86.4
20                            1.3          23386            80.2
21                            0.0          21323            71.9
22                            1.5           3985            83.8
24                            0.2          17779            82.7

                         Location 1  fraction_under18  fraction_above65
0        (40.83724, -73.9211399997)          0.298882          0.069483
1   (40.8522899998, -73.9109799997)          0.299634          0.064565
2   (40.8075800001, -73.9184800003)          0.305247          0.090473
3   (40.8151399998, -73.9078500002)          0.299508          0.087684
4   (40.8308399999, -73.9097899997)          0.311160          0.077565
5        (40.8476400003, -73.89989)          0.311266          0.075238
6   (40.8630699996, -73.8891599998)          0.283676          0.065579
7   (40.8251799997, -73.8941699997)          0.308954          0.083643
8   (40.8404800002, -73.8802600004)          0.306137          0.085446
10  (40.8434100004, -73.8597099997)          0.238837          0.102858
15  (40.8733400001, -73.8718599997)          0.262879          0.099433
16  (40.8663499998, -73.8999199996)          0.272631          0.085292
20  (40.8293900004, -73.8715400003)          0.280433          0.094277
21  (40.8190199998, -73.8605499998)          0.269998          0.119090
22  (40.8139299998, -73.8866399996)          0.299976          0.061070
24  (40.8221799998, -73.9209600004)          0.272220          0.119288

[16 rows x 52 columns]

In [51]:
len(bronx_pop_density_rental_filtered.index)/len(bronx_pop_density.index)

0.64

64% of all neighborhoods/zipcodes satisfy the criteria of having 70% or more of its housing units be rentals. I approached the question by understanding that I had to create a dataframe that filtered out all of the entries that had % Rental Units lower than 70. Then I understood that the total number of neighborhoods would be equal to the number of rows. Thus, I used the index function on the old and new filtered datasets. By dividing the two index values, I would get the percent.

# Part 4

Question 16
Indicate one question/part in this assignment that you find helpful in helping you understand an idea or method introduced in class. This could be a question/task that you knew right away how to do; one for which you kept encountering bugs/errors; or one that you needed to think a while or discuss with others first to figure out. (State which question/part and how it helps you with which idea/method.)

One question/part in this assignment that I found helpful in understanding an idea introduced in class were Question 11 and 12 because they helped me practice filtering datasets. While the coding portion of it wasn't challenging to figure out, it was helpful to be able to see how the dataset was changed after the filter was applied. 

Question 17
Write one thing that you find challenging or interesting in this assignment.

One thing that I found interesting in this assignment was the task in Question 14 where we had to filter the dataset by multiple columns. I found this interesting because it emulated the type of data analysis work that we would need to do in the real-world where a dataset would need to be analyzed through a variety of lenses.